### ISSUE TITLE
R windows install error

### ISSUE THREAD

**Issue by consumere** [yrobink/SBCK-R#1]
Hello
I´m having trouble installing SBCK on my windows machine.
..all other dependencies like "ROOPSD" worked.

I tried as in Readme " Rscript build.R -c -v -i    "
(I also tried the master branch...)
and get the following error:

` installing *source* package 'SBCK' ... (358ms)
   ** using staged installation
   ** libs
   g++  -std=gnu++11 -I"/include" -DNDEBUG  -I'AppData/Local/R/win-library/4.2/Rcpp/include' -I'AppData/Local/R/win-library/4.2/RcppEigen/include'   -I"D:/wslconda/xclim/SBCK/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall -gdwarf-2 -mfpmath=sse -msse2 -mstackrealign  -UNDEBUG -Wall -pedantic -g -O0 -c RcppExports.cpp -o RcppExports.o
   In file included from /AppData/Local/R/win-library/4.2/Rcpp/include/RcppCommon.h:30,
                    from /AppData/Local/R/win-library/4.2/RcppEigen/include/RcppEigenForward.h:26,
                    from /AppData/Local/R/win-library/4.2/RcppEigen/include/RcppEigen.h:25,
                    from RcppExports.cpp:4:
   AppData/Local/R/win-library/4.2/Rcpp/include/Rcpp/r/headers.h:66:10: fatal error: R.h: No such file or directory
      66 | #include <R.h>
         |          ^~~~~
   compilation terminated.
   make: *** [C:/PROGRA~1/R/R-42~1.1/etc/x64/Makeconf:260: RcppExports.o] Error 1
   ERROR: compilation failed for package 'SBCK'
─  removing '/AppData/Local/Temp/RtmpumjAT0/devtools_install_4520114c3d79/SBCK'
Error in `(function (command = NULL, args = character(), error_on_status = TRUE, …`:
! System command 'Rcmd.exe' failed
---
Exit status: 1
stdout & stderr: <printed>
---
Backtrace:
 1. devtools::load_all("SBCK")
 2. pkgload::load_all(path = path, reset = reset, recompile = recompile, …
 3. pkgbuild::compile_dll(path, quiet = quiet)
 4. pkgbuild:::install_min(path, dest = install_dir, components = "libs", args = if (needs_clean(path)) "--preclean", …
 5. pkgbuild::rcmd_build_tools("INSTALL", c(path, paste("--library=", dest, …
 6. pkgbuild::with_build_tools({ …
 7. withr::with_path(rtools_path(), code)
 8. base::force(code)
 9. base::withCallingHandlers(callr::rcmd_safe(..., env = env, spinner = FALSE, …
10. callr::rcmd_safe(..., env = env, spinner = FALSE, show = FALSE, …
11. callr:::run_r(options)
12. base::with(options, with_envvar(env, do.call(processx::run, c(list(bin, …
13. base::with.default(options, with_envvar(env, do.call(processx::run, …
14. base::eval(substitute(expr), data, enclos = parent.frame())
15. base::eval(substitute(expr), data, enclos = parent.frame())
16. callr:::with_envvar(env, do.call(processx::run, c(list(bin, args = real_cmdargs, …
17. base::force(code)
18. base::do.call(processx::run, c(list(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout), …
19. (function (command = NULL, args = character(), error_on_status = TRUE, …
20. base::throw(new_process_error(res, call = sys.call(), echo = echo, …
21. | base::signalCondition(cond)
22. (function (e) …
23. asNamespace("callr")$err$throw(e)
Execution halted`

regards,
chris

**Comment by yrobink** [comment]
Dear @consumere ,

In the error message, you can see `No such file or directory 66 | #include <R.h>`, which is a problem of R installation: the file `R.h` is missing.

**Comment by consumere** [comment]
Dear @yrobink ,
thank you for the hint. My Rcpp configuration was somehow incorrect. 
regards,
chris
